# Docker Compose for Thought Ramble Parser
version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - API_HOST=0.0.0.0
      - API_PORT=8000
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build:
      context: ./thought-ramble-parser
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./thought-ramble-parser:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  node_modules:
